services:
  - type: web
    name: resumeai-backend
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: /api/v1
      - key: SUPABASE_STORAGE_BUCKET
        value: resumes
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: CORS_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
