/**
 * Canonical Skill Aliases and Normalization Dictionary
 */
export const SKILL_ALIASES = {
  // Languages
  "js": "JavaScript",
  "javascript": "JavaScript",
  "ecmascript": "JavaScript",
  "ts": "TypeScript",
  "typescript": "TypeScript",
  "py": "Python",
  "python": "Python",
  "python3": "Python",
  "java": "Java",
  "cpp": "C++",
  "c++": "C++",
  "cplusplus": "C++",
  "c#": "C#",
  "csharp": "C#",
  "golang": "Go",
  "go": "Go",
  "rust": "Rust",
  "rb": "Ruby",
  "ruby": "Ruby",
  "php": "PHP",
  "swift": "Swift",
  "kt": "Kotlin",
  "kotlin": "Kotlin",

  // Frontend
  "html": "HTML5",
  "html5": "HTML5",
  "css": "CSS3",
  "css3": "CSS3",
  "react": "React",
  "reactjs": "React",
  "react.js": "React",
  "next": "Next.js",
  "nextjs": "Next.js",
  "next.js": "Next.js",
  "vue": "Vue.js",
  "vuejs": "Vue.js",
  "vue.js": "Vue.js",
  "angular": "Angular",
  "angularjs": "Angular",
  "tailwind": "Tailwind CSS",
  "tailwindcss": "Tailwind CSS",
  "redux": "Redux",
  "redux-toolkit": "Redux",
  "rtk": "Redux",

  // Backend
  "node": "Node.js",
  "nodejs": "Node.js",
  "node.js": "Node.js",
  "express": "Express.js",
  "expressjs": "Express.js",
  "express.js": "Express.js",
  "nest": "NestJS",
  "nestjs": "NestJS",
  "fastapi": "FastAPI",
  "django": "Django",
  "flask": "Flask",
  "springboot": "Spring Boot",
  "spring boot": "Spring Boot",
  "spring-boot": "Spring Boot",
  "graphql": "GraphQL",
  "rest": "REST APIs",
  "restful": "REST APIs",
  "rest api": "REST APIs",
  "rest apis": "REST APIs",

  // Databases
  "mongo": "MongoDB",
  "mongodb": "MongoDB",
  "postgres": "PostgreSQL",
  "postgresql": "PostgreSQL",
  "mysql": "MySQL",
  "redis": "Redis",
  "sqlite": "SQLite",
  "prisma": "Prisma",
  "mongoose": "Mongoose",

  // DevOps & Cloud
  "docker": "Docker",
  "k8s": "Kubernetes",
  "kubernetes": "Kubernetes",
  "aws": "AWS",
  "amazon web services": "AWS",
  "gcp": "Google Cloud",
  "google cloud platform": "Google Cloud",
  "google cloud": "Google Cloud",
  "ci/cd": "CI/CD",
  "cicd": "CI/CD",
  "github actions": "CI/CD",

  // Tools & CS
  "git": "Git",
  "github": "GitHub",
  "linux": "Linux",
  "dsa": "Data Structures",
  "data structures": "Data Structures",
  "algorithms": "Algorithms",
  "arrays": "Arrays",
  "array": "Arrays",
  "strings": "Strings",
  "string": "Strings",
  "hash tables": "Hash Tables",
  "hash map": "Hash Tables",
  "trees": "Trees & Graphs",
  "graphs": "Trees & Graphs",
  "dp": "Dynamic Programming",
  "dynamic programming": "Dynamic Programming",

  // Testing
  "jest": "Jest",
  "vitest": "Vitest",
  "playwright": "Playwright",
  "cypress": "Cypress"
};
