/**
 * Authoritative Public Documentation References
 * Verified, official documentation URLs for standard engineering technologies.
 */
export const AUTHORITATIVE_DOCS = {
  "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  "TypeScript": "https://www.typescriptlang.org/docs/",
  "React": "https://react.dev/learn",
  "Node.js": "https://nodejs.org/en/docs",
  "Express.js": "https://expressjs.com/",
  "MongoDB": "https://www.mongodb.com/docs/",
  "PostgreSQL": "https://www.postgresql.org/docs/",
  "Docker": "https://docs.docker.com/get-started/",
  "Git": "https://git-scm.com/doc",
  "REST APIs": "https://developer.mozilla.org/en-US/docs/Glossary/REST",
  "HTML": "https://developer.mozilla.org/en-US/docs/Web/HTML",
  "CSS": "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "HTML5": "https://developer.mozilla.org/en-US/docs/Web/HTML",
  "CSS3": "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "Python": "https://docs.python.org/3/",
  "Tailwind CSS": "https://tailwindcss.com/docs",
  "Data Structures": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
  "Algorithms": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
  "Arrays": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
  "Hash Maps": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
  "Strings": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
  "Stack": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
  "Problem Solving": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  "Next.js": "https://nextjs.org/docs",
  "Redis": "https://redis.io/docs/",
  "Vitest": "https://vitest.dev/guide/",
  "Jest": "https://jestjs.io/docs/getting-started",
  "CI/CD": "https://docs.github.com/en/actions",
  "Vite": "https://vitejs.dev/guide/",
  "Redux": "https://redux.js.org/introduction/getting-started",
  "GraphQL": "https://graphql.org/learn/",
  "Linux": "https://ubuntu.com/tutorials",
  "Nginx": "https://nginx.org/en/docs/",
};
