/**
 * Skill Aliases Dictionary.
 * Maps raw, case-insensitive, alternate, or misspelled representations to their Canonical Skill Name.
 */

export const SKILL_ALIASES = {
  // JavaScript & Variants
  "js": "JavaScript",
  "javascript": "JavaScript",
  "java script": "JavaScript",
  "vanilla js": "JavaScript",
  "vanillajs": "JavaScript",
  "es6": "JavaScript",
  "es6+": "JavaScript",
  "ecmascript": "JavaScript",

  // TypeScript
  "ts": "TypeScript",
  "typescript": "TypeScript",
  "type script": "TypeScript",

  // Python
  "python": "Python",
  "python3": "Python",
  "python 3": "Python",
  "py": "Python",

  // Java
  "java": "Java",
  "core java": "Java",
  "java 8": "Java",
  "java 11": "Java",
  "java 17": "Java",
  "java 21": "Java",

  // C++ / C / C#
  "cpp": "C++",
  "c++": "C++",
  "cplusplus": "C++",
  "c plus plus": "C++",
  "c": "C",
  "c#": "C#",
  "csharp": "C#",
  "c sharp": "C#",

  // Go / Rust / PHP / Ruby
  "go": "Go",
  "golang": "Go",
  "rust": "Rust",
  "php": "PHP",
  "ruby": "Ruby",
  "kotlin": "Kotlin",
  "swift": "Swift",

  // Web Foundations
  "html": "HTML",
  "html5": "HTML",
  "css": "CSS",
  "css3": "CSS",

  // React & Ecosystem
  "react": "React",
  "reactjs": "React",
  "react.js": "React",
  "react js": "React",
  "react-js": "React",
  "next": "Next.js",
  "nextjs": "Next.js",
  "next.js": "Next.js",
  "next js": "Next.js",
  "react native": "React Native",
  "reactnative": "React Native",
  "redux": "Redux",
  "redux toolkit": "Redux",
  "rtk": "Redux",

  // Other Frontend Frameworks
  "vue": "Vue.js",
  "vuejs": "Vue.js",
  "vue.js": "Vue.js",
  "vue js": "Vue.js",
  "angular": "Angular",
  "angularjs": "Angular",
  "angular.js": "Angular",
  "svelte": "Svelte",
  "sveltekit": "Svelte",
  "tailwind": "Tailwind CSS",
  "tailwindcss": "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  "bootstrap": "Bootstrap",

  // Node & Backend
  "node": "Node.js",
  "nodejs": "Node.js",
  "node.js": "Node.js",
  "node js": "Node.js",
  "express": "Express.js",
  "expressjs": "Express.js",
  "express.js": "Express.js",
  "express js": "Express.js",
  "nest": "NestJS",
  "nestjs": "NestJS",
  "nest.js": "NestJS",
  "django": "Django",
  "fastapi": "FastAPI",
  "fast api": "FastAPI",
  "flask": "Flask",
  "spring": "Spring Boot",
  "springboot": "Spring Boot",
  "spring boot": "Spring Boot",
  "graphql": "GraphQL",
  "rest": "REST APIs",
  "rest api": "REST APIs",
  "restful": "REST APIs",
  "restful api": "REST APIs",
  "restful apis": "REST APIs",
  "rest apis": "REST APIs",
  "grpc": "gRPC",

  // Databases
  "mongo": "MongoDB",
  "mongodb": "MongoDB",
  "mongo db": "MongoDB",
  "mongoose": "Mongoose",
  "postgres": "PostgreSQL",
  "postgresql": "PostgreSQL",
  "postgre sql": "PostgreSQL",
  "mysql": "MySQL",
  "my sql": "MySQL",
  "sqlite": "SQLite",
  "sqlite3": "SQLite",
  "redis": "Redis",
  "sql": "SQL",
  "supabase": "Supabase",
  "firestore": "Firebase Firestore",
  "firebase firestore": "Firebase Firestore",
  "prisma": "Prisma",
  "prisma orm": "Prisma",

  // DevOps & Cloud
  "docker": "Docker",
  "dockerfile": "Docker",
  "docker-compose": "Docker",
  "docker compose": "Docker",
  "k8s": "Kubernetes",
  "kubernetes": "Kubernetes",
  "aws": "AWS",
  "amazon web services": "AWS",
  "github actions": "GitHub Actions",
  "github-actions": "GitHub Actions",
  "ci/cd": "CI/CD",
  "cicd": "CI/CD",
  "continuous integration": "CI/CD",
  "linux": "Linux",
  "ubuntu": "Linux",
  "nginx": "Nginx",

  // Core CS & Problem Solving
  "dsa": "Data Structures",
  "data structure": "Data Structures",
  "data structures": "Data Structures",
  "algo": "Algorithms",
  "algorithm": "Algorithms",
  "algorithms": "Algorithms",
  "problem solving": "Problem Solving",
  "problem-solving": "Problem Solving",
  "competitive programming": "Problem Solving",
  "arrays": "Arrays",
  "array": "Arrays",
  "hashmap": "Hash Maps",
  "hash map": "Hash Maps",
  "hash maps": "Hash Maps",
  "hash table": "Hash Maps",
  "hash tables": "Hash Maps",
  "hash-table": "Hash Maps",
  "hashing": "Hash Maps",
  "strings": "Strings",
  "string": "Strings",
  "two pointers": "Two Pointers",
  "two-pointers": "Two Pointers",
  "stack": "Stack",
  "stacks": "Stack",
  "queue": "Queue",
  "queues": "Queue",
  "trees": "Trees",
  "tree": "Trees",
  "binary tree": "Trees",
  "binary search tree": "Trees",
  "graphs": "Graphs",
  "graph": "Graphs",
  "dp": "Dynamic Programming",
  "dynamic programming": "Dynamic Programming",
  "binary search": "Binary Search",
  "sorting": "Sorting",
  "arrays & hashing": "Arrays",

  // Tools & Testing
  "git": "Git",
  "github": "GitHub",
  "postman": "Postman",
  "vite": "Vite",
  "webpack": "Webpack",
  "jest": "Jest",
  "vitest": "Vitest",
  "playwright": "Playwright",
  "cypress": "Cypress",
};
